# Generated by Django 3.2.6 on 2021-08-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eccomerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='items',
            field=models.ManyToManyField(to='eccomerce.Producto'),
        ),
    ]
